version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    volumes:
      - ./flask/app:/app/app
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"